<?php /** * Brands sldier */ ?>
<?php $helper = $this->getHelperData(); $brands = $this->getLoadedBrands(); ?>
<?php if ($brands): ?>
    <?php $sliderClasses = ''; $imgClasses = ''; $isResponsive = $this->getIsResponsive();
    if ($isResponsive === NULL) { $isResponsive = true; } $breakpoints = $this->getBreakpoints();
    if ($breakpoints === NULL) { $breakpoints = '[0, 1], [320, 2], [480, 2], [768, 3], [992, 4], [1200, 5]'; } $showItems = $this->getShowItems();
    if (!$showItems) { $showItems = 5; } $pagination = $this->getPagination(); $timeout = $this->getTimeout();
    if ($timeout === NULL) { $timeout = intval($helper->getCfg('slider/timeout')); }
    else { $timeout = intval($timeout); } $move = $this->getMove();
    if ($move === NULL) { $move = 0; }
    else { $move = intval($move); } $loop = $this->getLoop();
    if ($loop === NULL)
    {
        $loop = $helper->getCfg('slider/loop');
    }
    $speed = intval($helper->getCfg('slider/speed'));
    $autoSpeed = intval($helper->getCfg('slider/auto_speed'));
    $pause = $helper->getCfg('slider/pause');
    $lazy = $helper->getCfg('slider/lazy');
    if($isResponsive)
    {
        $sliderClasses .= ' itemslider-responsive';
    }
    $sliderId = "itemslider-brands-{$this->getFrontendHash()}"; ?>
    <?php $brandAttrLabel = $this->getBrandAttributeTitle();
    if ($lazy) { $srcAttribute = 'data-src'; $imgClasses = 'class="lazyOwl"'; }
    else { $srcAttribute = 'src'; $imgClasses = ''; } ?>
    <!-- <script type="text/javascript" src="<?php echo $this->getOwlUrl();?>"></script> -->
    <h3 class="section-title padding-right"><?php echo $this->getBlockName(); ?></h3>
    <div class="itemslider-wrapper brand-slider-wrapper slider-arrows1 slider-arrows1-pos-top-right slider-pagination1 slider-pagination1-centered">
        <div id="<?php echo $sliderId; ?>" class="itemslider<?php if($sliderClasses) echo $sliderClasses; ?> brand-slider">
            <?php foreach ($brands as $brand): ?>
                <?php $brandPageUrl = $this->getBrandPageUrl($brand);
                $brandImageUrl = $this->getBrandImageUrl($brand);
                $brandDetailsHtml = '';
                if (!$helper->isShowImage())
                {
                    $brandDetailsHtml = '<span class="brand-name-wrapper"><span class="brand-name">'. $brand .'</span></span>';
                }
                else
                {
                    if ($brandImageUrl)
                    {
                        $brandPageUrl ? $imgTitle='' : $imgTitle="title=\"{$brandAttrLabel}: {$brand}\"";
                        $brandDetailsHtml = "<img {$imgClasses} {$srcAttribute}=\"{$brandImageUrl}\" alt=\"{$brand}\" {$imgTitle}/>";
                    }
                    else
                    {
                        if ($helper->isShowImageFallbackToText())
                        {
                            $brandDetailsHtml = '<span class="brand-name-wrapper"><span class="brand-name">'. $brand .'</span></span>';
                        }
                    }
                }
                ?>
                <?php
                if ($brandDetailsHtml): ?>
                    <div class="item">
                    <?php if ($brandPageUrl): ?>
                        <a class="fade-on-hover" href="<?php echo $brandPageUrl; ?>" title="<?php echo __('Click to see more products from %s', $brand); ?>"><?php echo $brandDetailsHtml; ?></a>
                    <?php else: ?>
                        <?php echo $brandDetailsHtml; ?>
                    <?php endif; ?>
                    </div>
                <?php endif; ?>
            <?php endforeach; ?>
        </div><!-- end: itemslider --></div><!-- end: itemslider-wrapper -->

    <script type="text/javascript">
    require(['jquery', 'owlcarousel'], function(){
        jQuery(function(jQuery) {

            var owl = jQuery('#<?php echo $sliderId; ?>');
            owl.owlCarousel({

            <?php if ($lazy): ?>
                lazyLoad: true,
            <?php endif; ?> <?php if (!$isResponsive): ?>
                responsive: false,
                items: <?php echo $showItems; ?>,
            <?php else: ?>
                itemsCustom: [ <?php echo $breakpoints; ?> ],
                responsiveRefreshRate: 50,
            <?php endif; ?> <?php if ($speed): ?>
                slideSpeed: <?php echo $speed; ?>,
            <?php endif; ?> <?php if ($autoSpeed): ?>
                paginationSpeed: <?php echo $autoSpeed; ?>,
            <?php endif; ?> <?php if ($move !== 1): ?>
                scrollPerPage: true,
            <?php endif; ?> <?php if ($timeout): ?>
                autoPlay: <?php echo $timeout; ?>,
            <?php endif; ?> <?php if ($pause): ?>
                stopOnHover: true,
            <?php endif; ?> <?php if ($loop): ?>
                rewindNav: true,
                rewindSpeed: 600,
            <?php else: ?>
                rewindNav: false,
            <?php endif; ?> <?php if ($pagination): ?>
                pagination: true,
                paginationSpeed: 600,
            <?php else: ?>
                pagination: false,
            <?php endif; ?> navigation: true,
                navigationText: false

            }); 

        });    
    });
//]]>
</script><?php endif; ?>