<?php
/**
 * Apptha
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://www.apptha.com/LICENSE.txt
 *
 * ==============================================================
 *                 MAGENTO EDITION USAGE NOTICE
 * ==============================================================
 * This package designed for Magento COMMUNITY edition
 * Apptha does not guarantee correct work of this extension
 * on any other Magento edition except Magento COMMUNITY edition.
 * Apptha does not provide extension support in case of
 * incorrect edition usage.
 * ==============================================================
 *
 * @category    Apptha
 * @package     Apptha_Marketplace
 * @version     1.1
 * @author      Apptha Team <developers@contus.in>
 * @copyright   Copyright (c) 2016 Apptha. (http://www.apptha.com)
 * @license     http://www.apptha.com/LICENSE.txt
 *
 * */
?>
<div class="order-manage">
   <?php
$OrderItemCollection = $block->getCollection ();
if ($OrderItemCollection->getSize () > 0) {
    ?>
             
 <div class="table-wrapper orders-history">
		<table class="data table table-order-items history"
			id="my-orders-table">
			<caption class="table-caption"><?php echo __('Recent Orders');?></caption>
			<tr>
				<th><?php echo __('Order #');?></th>
				<th><?php echo __('Date');?></th>
				<th><?php echo __('Product Details');?></th>
				<th><?php echo __('Total Product Amount');?></th>
				<th><?php echo __('Commission');?></th>
				<th><?php echo __('Seller Amount');?></th>
				<th><?php echo __('Status');?></th>
				<th><?php echo __('Action');?></th>
			</tr>
		  <?php
    
foreach ( $OrderItemCollection as $item ) {
        $orderId = $item->getOrderId ();
        $sellerId = $item->getSellerId ();
        $customerId = $item->getCustomerId ();
        $orderDetails = $block->getOrderDetails ( $orderId, $sellerId, $customerId );
        $productName = $block->getProductDetails ( $orderId, $sellerId );
        $createdAt = $orderDetails ['created_at'];
        $modifiedDate = new DateTime ( $createdAt );
        $createdAt = $modifiedDate->format ( 'm/d/Y' );
        $currencyCode = $item->getOrderCurrencyCode ();
        $currencySymbol = $block->getCurrencySymbol ( $currencyCode );
        if (empty ( $currencySymbol )) {
            $currencySymbol = $currencyCode;
        }
        ?>   
                       <tr>
				<td><?php echo $item->getIncrementId();?></td>
				<td><?php echo $createdAt;?></td>
				<td><?php echo $productName; ?></td>
				<td><?php echo $currencySymbol.round($item->getSellerProductTotal(),2);?></td>
				<td><?php echo $currencySymbol.round($item->getCommission(),2); ?></td>
				<td><span class="price"><?php echo $currencySymbol.round($item->getSellerAmount(),2);?></span></td>
				<td><?php echo ucfirst($item->getStatus());?></td>
				<td><a
					href="<?php echo $block->getUrl('marketplace/order/vieworder/id/'.$orderId)?>"
					class="action view"> <span><?php echo __('View');?></span>
				</a></td>
			</tr>
         <?php }?>    
      </table>
		<div class="toolbar-bottom"></div>
	</div>
   <?php

} else {
    echo __ ( 'No Records were Found' );
}
?>
</div>