<?php
/**
 * Apptha
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://www.apptha.com/LICENSE.txt
 *
 * ==============================================================
 *                 MAGENTO EDITION USAGE NOTICE
 * ==============================================================
 * This package designed for Magento COMMUNITY edition
 * Apptha does not guarantee correct work of this extension
 * on any other Magento edition except Magento COMMUNITY edition.
 * Apptha does not provide extension support in case of
 * incorrect edition usage.
 * ==============================================================
 *
 * @category    Apptha
 * @package     Apptha_Marketplace
 * @version     1.1
 * @author      Apptha Team <developers@contus.in>
 * @copyright   Copyright (c) 2016 Apptha. (http://www.apptha.com)
 * @license     http://www.apptha.com/LICENSE.txt
 *
 */
$sellerId = $this->getRequest ()->getParam ( 'id' );
$isSellerReviewEnabled = $block->isSellerReviewEnabled ();
if ($isSellerReviewEnabled == 1) {
    ?>
<div class="block">
	<div class="block-title">
		<strong><span><?php echo __('Feedback Ratings'); ?></span></strong>
	</div>
<?php
    $ratings = $block->getRatingsData ( $sellerId );
    $percent = $ratings ['percent'];
    $count = $ratings ['count'];
    ?>
<div class="individual-star-ratings">
		<ul class="rating-histogram">
			<li class="advanced-font-small"><span><?php
    /**
     * Show 5 star ratings
     */
    echo __ ( '5 Stars' );
    ?></span>
				<div class="rating-bars">
					<div class="progress  " style="width:<?php
    if (isset ( $percent ['five'] )) {
        echo ceil ( $percent ['five'] );
    } else {
        echo 0;
    }
    ?>%; !important;"></div>
				</div> &nbsp;<strong><?php
    
if (isset ( $count ['five'] )) {
        echo $count ['five'];
    } else {
        echo 0;
    }
    ?> </strong></li>
			<li class="advanced-font-small"><span><?php
    /**
     * Show 4 star ratings
     */
    echo __ ( '4 Stars' );
    ?></span>
				<div class="rating-bars">
					<div class="progress  " style="width:<?php
    if (isset ( $percent ['four'] )) {
        echo ceil ( $percent ['four'] );
    } else {
        echo 0;
    }
    ?>%; !important;"></div>
				</div> &nbsp;<strong><?php
    
if (isset ( $count ['four'] )) {
        echo $count ['four'];
    } else {
        echo 0;
    }
    ?>  </strong></li>
			<li class="advanced-font-small"><span><?php
    /**
     * Show 3 star ratings
     */
    echo __ ( '3 Stars' );
    ?></span>
				<div class="rating-bars">
					<div class="progress  " style="width:<?php
    if (isset ( $percent ['three'] )) {
        echo ceil ( $percent ['three'] );
    } else {
        echo 0;
    }
    ?>%; !important;"></div>
				</div> &nbsp;<strong><?php
    
if (isset ( $count ['three'] )) {
        echo $count ['three'];
    } else {
        echo 0;
    }
    ?> </strong></li>
			<li class="advanced-font-small"><span><?php
    /**
     * Show 2 star ratings
     */
    echo __ ( '2 Stars' );
    ?></span>
				<div class="rating-bars">
					<div class="progress  " style="width:<?php
    if (isset ( $percent ['two'] )) {
        echo ceil ( $percent ['two'] );
    } else {
        echo 0;
    }
    ?>%; background-color:  !important;"></div>
				</div> &nbsp;<strong><?php
    
if (isset ( $count ['two'] )) {
        echo $count ['two'];
    } else {
        echo 0;
    }
    ?>  </strong></li>
			<li class="advanced-font-small"><span><?php
    /**
     * Show 1 star ratings
     */
    echo __ ( '1 Stars' );
    ?></span>
				<div class="rating-bars">
					<div class="progress  " style="width:<?php
    if (isset ( $percent ['one'] )) {
        echo ceil ( $percent ['one'] );
    } else {
        echo 0;
    }
    ?>%; background-color: !important;"></div>
				</div> &nbsp;<strong><?php
    
if (isset ( $count ['one'] )) {
        echo $count ['one'];
    } else {
        echo 0;
    }
    ?> </strong></li>
		</ul>
		<div class="positive_review_ratings">
			<div class="positive_review_positive"><?php echo __('Positive'); ?></div>
			<div class="positive_review_neutral"><?php echo __('Neutral'); ?></div>
			<div class="positive_review_negative"><?php echo __('Negative'); ?></div>
		</div>
	</div>
	<div class="seller-review">
<?php
    $reviews = $block->getReviewcount ( $sellerId );
    if (count ( $reviews ) > 0) {
        ?>
 <a href='<?php echo $block->getReviewUrl($sellerId); ?>'> <?php
        echo __ ( 'View Reviews ' );
        ?> </a> 
<?php
    }
    ?>

<?php
    if ($block->getLoggedInCustomerId () != '') {
        $canReview = $block->canReview ( $block->getLoggedInCustomerId (), $sellerId );
        if ($canReview == 1) {
            ?>
<h5>
			<a
				href='<?php echo $block->getWriteReviewUrl($sellerId).'#seller_review'; ?>'> <?php echo __('Write a Review to this Seller'); ?> </a>
		</h5>
 
<?php
        }
    } else {
        ?>
<h5><?php echo __('Have you bought something from this seller?').' '; ?></h5>
		<a class="mp_view_allreview"
			href="<?php echo $block->getLoginUrl(); ?>"><?php echo __('Login to Review'); ?></a>
<?php } ?>
</div>
</div>

<?php } ?>