<?php
/**
 * Apptha
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://www.apptha.com/LICENSE.txt
 *
 * ==============================================================
 *                 MAGENTO EDITION USAGE NOTICE
 * ==============================================================
 * This package designed for Magento COMMUNITY edition
 * Apptha does not guarantee correct work of this extension
 * on any other Magento edition except Magento COMMUNITY edition.
 * Apptha does not provide extension support in case of
 * incorrect edition usage.
 * ==============================================================
 *
 * @category    Apptha
 * @package     Apptha_Marketplace
 * @version     1.1
 * @author      Apptha Team <developers@contus.in>
 * @copyright   Copyright (c) 2016 Apptha. (http://www.apptha.com)
 * @license     http://www.apptha.com/LICENSE.txt
 *
 */
?>
<div>
	<h3><?php
echo __ ( 'Reviews and Ratings of' ) . ' ' . $block->getStoreName ();
?></h3> 
<?php
$sellerReviews = $block->getCollection ();
if (count ( $sellerReviews ) >= 1) {
    ?>
      <div class="toolbar-bottom">
		<div class="toolbar bottom">
            <?php echo $block->getPagerHtml(); ?>
         </div>
	</div>
<?php
    foreach ( $sellerReviews as $sellerReview ) {
        ?>
      <div class="all_review_container">
		<div class="all_reviews_details">
			<p class="all_reviews_block">
                    <?php
        /**
         * Display seller rating
         */
        if ($sellerReview->getRating () == 1) {
            ?>
                        <label class="all_review_rating"
					style="width: 20%;"></label>
                    <?php } elseif ($sellerReview->getRating() == 2) { ?>
                        <label class="all_review_rating"
					style="width: 40%;"></label>
                    <?php } elseif ($sellerReview->getRating() == 3) { ?>
                        <label class="all_review_rating"
					style="width: 60%;"></label>
                    <?php } elseif ($sellerReview->getRating() == 4) { ?>
                        <label class="all_review_rating"
					style="width: 80%;"></label>
                    <?php } else { ?>
                        <label class="all_review_rating"
					style="width: 100%;"></label>
                    <?php } ?>   
                </p>
			<b><?php echo $block->getCustomerName($sellerReview->getCustomerId()) . '</br>'; ?></b>
			<span>
                    <?php
        
$date = $sellerReview->getCreatedAt ();
        echo $newDate = date ( 'M j, Y', strtotime ( $date ) ) . '</br>';
        ?>               
                </span>
		</div>
		<p
			class="all_reviews_comments <?php if(strlen($sellerReview->getReview()) > 700){?> product_review <?php } ?>">
        <?php echo $sellerReview->getReview() . '</br>'; ?> 
            </p>
		<span class="read-more"
			<?php if(strlen($sellerReview->getReview()) < 700){?>
			style='display: none;' <?php } ?>><?php echo __('Read More'); ?></span>
	</div>
	<div class="clear"></div>
<?php
    }
    ?>
      <div class="toolbar-bottom">
		<div class="toolbar bottom">
            <?php echo $block->getPagerHtml(); ?>
         </div>
	</div>
<?php
} else {
    ?>
<p><?php echo __("We couldn't find any records."); ?></p>
<?php
}
?> 
<?php
/**
 * Seller review form
 */
?>
<div id="seller_review">
<?php
$sellerId = $this->getRequest ()->getParam ( 'seller_id' );
$write = $this->getRequest ()->getParam ( 'write' );
if (! empty ( $sellerId ) && $write == 1) {
    if ($block->getLoggedInCustomerId () != $sellerId) {
        $canReview = $block->canReview ( $block->getLoggedInCustomerId (), $sellerId );
        if ($canReview == 1) {
            ?>
<ul>
			<div class="mp_seller_rating">
				<form action='<?php echo $block->saveReviewUrl(); ?>'
					id="seller_review_form" method="post">
					<p class="mp_seller_comments">
						<label for="sellername"> <?php echo __('Name:'); ?>  </label> <input
							type="text"
							value="<?php echo $block->getCustomerName($block->getLoggedInCustomerId()); ?>"
							readonly />
					</p>
					<p class="mp_seller_comments">
						<label for="feedback"> <?php echo __('Feedback about seller:'); ?>  </label>
						<textarea id="feedback" rows="9" cols="49" name="feedback"
							class="input-text" data-validate="{required:true}"></textarea>
					</p>
					<input type="hidden" name="seller_id"
						value="<?php echo $sellerId; ?>" /> <label class="mp_seller_left"
						for="rating"><?php echo __('Rate Seller:'); ?>  </label>
					<ul class="mp_seller_rate_options">
						<li class="user-rating" id="set-user-rating"></li>
						<li><input id="ratings_1" type="radio" name="rating" value="1"></li>
						<li><input id="ratings_2" type="radio" name="rating" value="2"></li>
						<li><input id="ratings_3" type="radio" name="rating" value="3"></li>
						<li><input id="ratings_4" type="radio" name="rating" value="4"></li>
						<li><input id="ratings_5" type="radio" name="rating" value="5"></li>
					</ul>
					<div style="display: none;" id="rating-error"><?php echo __('Kindly select any one of the option.'); ?></div>
					<button type="submit" class="button"
						title="<?php echo __('Submit Review') ?>" name="submit_review">
						<span><span><?php echo __('Submit') ?></span></span>
					</button>
				</form>
			</div>
		</ul>
<?php
        }
    }
}
?>
</div>
</div>

<script>
require([
    'jquery',
    'mage/mage'
], function($){
    var dataForm = $('#seller_review_form');
    var ignore = null;
    dataForm.mage('validation', {
            ignore: ignore ? ':hidden:not(' + ignore + ')' : ':hidden'
        }).find('input:text').attr('autocomplete', 'off');

    $("#seller_review_form").on('submit',(function(e){ 
    if($("input[name=rating]:checked").val() == undefined){  
    $('#rating-error').show(); 
    $('#rating-error').css({"color": "#e02b27","font-size": "1.2rem"});     
    return false;     
    }else{
    $('#rating-error').hide();    
    }       
    }));    
    
});
</script>
