<?php
/**
 * Apptha
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://www.apptha.com/LICENSE.txt
 *
 * ==============================================================
 *                 MAGENTO EDITION USAGE NOTICE
 * ==============================================================
 * This package designed for Magento COMMUNITY edition
 * Apptha does not guarantee correct work of this extension
 * on any other Magento edition except Magento COMMUNITY edition.
 * Apptha does not provide extension support in case of
 * incorrect edition usage.
 * ==============================================================
 *
 * @category    Apptha
 * @package     Apptha_Marketplace
 * @version     1.1
 * @author      Apptha Team <developers@contus.in>
 * @copyright   Copyright (c) 2016 Apptha. (http://www.apptha.com)
 * @license     http://www.apptha.com/LICENSE.txt
 *
 */
?>
<?php

/**
 * Checking for configurable status
 */
$status = 0;
$productTypes = $block->getProductTypes ();
if (in_array ( 'configurable', $productTypes )) {
    $status = 1;
}
if ($status == 1) {
    
    $productId = $this->getRequest ()->getParam ( 'product_id' );
    $typeId = '';
    if (! empty ( $productId )) {
        $productData = $block->getConfigurableProductData ( $productId );
        $typeId = $productData->getTypeId ();
    }
    
    ?>
<?php

    /**
     * This template files contains configurable product form
     */
    ?>
<div id="marketplace-configurble-product-content"
	class="fieldset marketplace-configurble-product"
	<?php if(count($productTypes) != 1 && $typeId != 'configurable'){ ?>
	style="display: none;" <?php } ?>>
	<?php
    if ($typeId == 'configurable') {
        ?>
	<input type="hidden" value="1" id="is_configurable_product"
		name="is_configurable_product">
	<?php
    } else {
        ?>
	<input type="hidden" value="0" id="is_configurable_product"
		name="is_configurable_product">
	<?php } ?>
	<input type="hidden" id="current_product_id"
		value="<?php echo $productId; ?>" name="product_id" />
	<h2 class="legend"><?php echo __('Configurations'); ?></h2>
	<div class="note" data-role="product-create-configuration-info">
<?php echo __('Configurable products allow customers to choose options (Ex: shirt color).'); ?>
<?php echo __('You need to create a simple product for each configuration (Ex: a product for each color).'); ?>
</div>
	<button id="btn_configurable_product" type="button"
		class="action submit primary"
		title="<?php echo __('Create Configurations'); ?>">
		<span><?php echo __('Create Configurations'); ?></span>
	</button>
	<div id="configurable_variant_error" style="display: none; color: red;"><?php echo __('Kindly create configurations before save this product'); ?></div>
	<div id="current_variants" style="display: none;">
		<strong><?php echo __('Current Variations'); ?></strong>
	</div>
	<div id="existing_configurable_section_content_form"
		class="configurable_section_content_form">
<?php
    
if (! empty ( $productId ) && $typeId == 'configurable') {
        $productAttributes = $productData->getTypeInstance ( true )->getConfigurableAttributes ( $productData );
        ?>
<strong><?php echo __('Current Variations'); ?></strong>
		<table>
			<tr>
				<th><?php echo __('Images'); ?></th>
				<th><?php echo __('SKU'); ?></th>
				<th><?php echo __('Quantity'); ?></th>
<?php foreach($productAttributes as $productAttribute){ ?>
<th><?php
            echo $block->getConfigurableProductAttributeLabel ( $productAttribute->getProductAttribute ()->getAttributeCode () );
            ?></th>
<?php } ?>
<th><?php echo __('Price'); ?></th>
			</tr>
<?php
        /**
         * Getting used product data's
         */
        $usedProductDatas = $block->getUsedAssociatedProductData ( $productData );
        $mediaImageUrl = $block->getSimpleProductMediaImageUrl ();
        foreach ( $usedProductDatas as $usedProductData ) {
            $simpleProductData = $block->getConfigurableProductData ( $usedProductData );
            ?>
<tr>
				<td><input type="hidden" value="1"
					id="configurable_associated_product_flag" />
<?php
            $simpleProductImage = $simpleProductData->getImage ();
            if (! empty ( $simpleProductImage ) && $simpleProductImage != 'undefined') {
                ?>
<img
					src="<?php echo $mediaImageUrl.DIRECTORY_SEPARATOR.$simpleProductImage; ?>"
					alt="<?php echo $simpleProductImage; ?>" height="200" width="200">
<?php } ?>
</td>
				<td><?php echo $simpleProductData->getSku(); ?></td>
				<td>
<?php  echo $block->getQtyForConfigurableAssoicatedProduct($simpleProductData->getId()); ?>
</td>
<?php foreach($productAttributes as $productAttribute){ ?>
<td><?php
                $optionId = $simpleProductData->getData ( $productAttribute->getProductAttribute ()->getAttributeCode () );
                $attributeData = $simpleProductData->getResource ()->getAttribute ( $productAttribute->getProductAttribute ()->getAttributeCode () );
                if ($attributeData->usesSource ()) {
                    echo $attributeData->getSource ()->getOptionText ( $optionId );
                }
                ?></td>
<?php } ?>
<td><?php
            
echo round ( $simpleProductData->getPrice (), 2 );
            echo ' [' . $block->getAssociatedVariantsBaseCurrency () . '] ';
            ?></td>
			</tr>
<?php  } ?>
</table>
<?php } ?>
</div>
	<div id="configurable_section_content_form"
		class="configurable_section_content_form"></div>
</div>

<div id="configurable-product-form" class="configurable-product-form"
	style="display: none;">
<div class="cpf_inner">	
<?php
    /**
     * Create Product Configurations
     */
    ?>
<h2 class="legend"><?php echo __('Create Product Configurations'); ?></h2>
	<div id="select-attributes-error" style="display: none;"><?php echo __('Please, select attribute(s)'); ?></div>
	<div id="attribute-options-error" style="display: none; color: red;"><?php echo __('Select options for all attributes'); ?></div>
	<div class="steps-wizard">
	<div class="steps-wizard-navigation">
		<ul class="configurable-product-status nav-bar">
			<li id="select-attribute-status" class="active"><span><?php echo __('Select Attributes'); ?></span></li>
			<li id="attribute-values-status"><span><?php echo __('Attribute Values'); ?></span></li>
			<li id="bulk-images-price-status"><span><?php echo __('Bulk Images & Price'); ?></span></li>
			<li id="summary-status"><span><?php echo __('Summary'); ?></span></li>
		</ul>
		<div class="nav-bar-outer-actions">
		<span id="btn_configurable_product_cancel" style="color: #006bb4;"><?php echo __('Cancel'); ?></span>
		<div class="action-wrap action-wrap-next">
		<button disabled="disabled" id="btn_configurable_product_back"
			type="button" class="action submit primary"
			title="<?php echo __('Back'); ?>">
			<span><?php echo __('Back'); ?></span>
		</button>
		</div>
		
		<button id="btn_configurable_product_next" type="button"
			class="action submit primary action-default action-primary action-next-step" title="<?php echo __('Next'); ?>">
			<span><?php echo __('Next'); ?></span>
		</button>
		
		<button id="btn_configurable_product_generate" type="button"
			style="display: none;" class="action submit primary"
			title="<?php echo __('Generate Product'); ?>">
			<span><?php echo __('Generate Product'); ?></span>
		</button>	
		</div>			
<div class="attributes_content">
<?php
    /**
     * Select Attributes
     */
    ?>
<div id="select-attribute">
			<form action="<?php echo $block->getConfigurableOptionsUrl(); ?>"
				method="POST" enctype="multipart/form-data"
				class="configurable_attribute_form" id="configurable_attribute_form">
				<input type="hidden" id="current_configurable_product_id"
					value="<?php echo $productId; ?>" name="product_id" />
<?php
    if (! empty ( $productId )) {
        ?>
<p>
<?php echo __("You cant't remove or add an attribute(s)."); ?>
</p>
<?php } ?>
<label class="label"><span><?php echo __('Select Attributes'); ?></span></label>
				<div id="select-attributes-list"></div>
			</form>
		</div>

<?php
    /**
     * Attribute Values
     */
    ?>
<div id="attribute-values" style="display: none;">
			<form action="<?php echo $block->getConfigurableOptionsUrl(); ?>"
				method="POST" enctype="multipart/form-data"
				class="configurable_attribute_form" id="configurable_options_form">
				<label class="label"><span><?php echo __('Attribute Values'); ?></span></label>
				<div id="attribute-values-list"></div>
				<input type="hidden" name="product_id"
					value="<?php echo $productId; ?>" />
			</form>
		</div>

<?php
    /**
     * Bulk Images & Price
     */
    ?>
<div id="bulk-images-price" style="display: none;">
			<label class="label"><span><?php echo __('Bulk Images, Price, and Quantity'); ?></span></label>
			<div id="bulk-images-list"></div>
			<input type="hidden" name="configurable_product_id"
				value="<?php echo $productId; ?>" />
		</div>

<?php
    /**
     * Summary
     */
    ?>
<div id="summary" style="display: none;">
			<label class="label"><span><?php echo __('Summary'); ?></span></label>
			<div id="summary-content"></div>
		</div>
</div>
	</div>
	</div>
	<div id="configurable-product-loader" style="display: none;"
		class="cssload-jumping">
		<span></span><span></span><span></span><span></span><span></span>
	</div>
	<input type="hidden" id="variants_generate_flag" value="">
</div>

<?php
    /**
     * Js code for configurable product
     */
    ?>
    </div>
<script>
       require([
                "jquery",
                "mage/calendar"
            ], function($){    	     	   
    	   $('#btn_configurable_product_generate').on('click', function(e) {
    		   configurableAssociatedProductFlag = 1;  
    		   $('#variants_generate_flag').val('1'); 
    		   $('#configurable_variant_error').hide();     	        
    		   var configurableProductClone = $('#configurable_product_prepared_data').html();                    
               $('#configurable_section_content_form').html(configurableProductClone);
               $('#configurable_product_prepared_data').html('');  
               $('#configurable-product-form').hide(); 
               $('#current_variants').show(); 
               $('#select-attribute').show();
        	   $('#select-attribute-status').addClass('active');
        	   $('#summary').hide('active');
        	   $('#summary-status').removeClass('active'); 
        	   $('#btn_configurable_product_next').show();
        	   $('#btn_configurable_product_generate').hide(); 
        	   $('#existing_configurable_section_content_form').hide();       	                                
    	   });      	   

    	   $('#btn_configurable_product_next').on('click', function(e) {        	   
    	   if($('#bulk-images-price').is(":visible")){
        	   
    		   var bulkValidateFlag = typeValidateFlag = 0;
        	   var configurablePriceChecked = $('input[name="configurable_price"]:checked').val();
        	   var configurableQtyChecked = $('input[name="configurable_qty"]:checked').val();
            
        	   if(configurablePriceChecked == 'price_unique'){
        	   var priceSelectUniqueValue = $('#price_select_unique').val();
        	   if(priceSelectUniqueValue == ''){
        		    bulkValidateFlag = 1; 
               }else{
               $(".price_unique_value_for_validate_"+priceSelectUniqueValue).each(function(){
                       if($(this).val() == '' ){
                       bulkValidateFlag = 1;   
                       }      
                       if(!$.isNumeric($(this).val())){
                           typeValidateFlag = 1;   
                           }      	            
                       }); 
               }          		         	   
               }

        	   if(configurablePriceChecked == 'price_all'){  
               $(".price_all_value_for_validate").each(function(){
               if($(this).val() == ''){
               bulkValidateFlag = 1;   
               }     
               if(!$.isNumeric($(this).val())){
                   typeValidateFlag = 1;   
                   }       	            
               });    		         	   
               }

        	   if(configurableQtyChecked == 'qty_unique'){
        	 	   var qtySelectUniqueValue = $('#qty_select_unique').val();
            	   if(qtySelectUniqueValue == ''){
            		    bulkValidateFlag = 1; 
                   }else{
                   $(".qty_unique_value_for_validate_"+qtySelectUniqueValue).each(function(){
                           if($(this).val() == '' ){
                           bulkValidateFlag = 1;   
                           }

                           if(!$.isNumeric($(this).val())){
                           typeValidateFlag = 1;   
                           }                      
                             
                           }); 
                   }  		         	   
               }

               if(configurableQtyChecked == 'qty_all'){  
               $(".qty_all_value_for_validate").each(function(){
               if($(this).val() == ''){
               bulkValidateFlag = 1;   
               } 
               if(!$.isNumeric($(this).val())){
                   typeValidateFlag = 1;   
                   }            	            
               });    		         	   
               }	

               if(bulkValidateFlag == 1){
               $("#bulk_price_qty_error_msg").show();
               return false;      
               }else{
               $("#bulk_price_qty_error_msg").hide();    
               }	

               if(typeValidateFlag == 1){
                   $("#type_price_qty_error_msg").show();
                   return false;      
                   }else{
                   $("#type_price_qty_error_msg").hide();    
                   }


               	   
        	           	   
    	   $('#bulk-images-price').hide();  
    	   $('#summary').show();
    	   $('#summary-status').addClass('active');   
    	   
    	   $('#btn_configurable_product_next').hide();
    	   $('#btn_configurable_product_generate').show();  	      
    	      	   
    	  
    	   $('#configurable_product_bulk_form').submit();    	      	  
    	   }      
    	   
           if($('#attribute-values').is(":visible")){
           var optionsCheckboxCount = 0;
           var previousOptionClass = currentOptionClass = selectedClass = '';
           var classNumItems = $('.attribute-options-ul').length;                     
    	   $(".attribute-options-checkbox").each(function(){
    	   currentOptionClass = $(this).attr('title');    	
    	   if(previousOptionClass == '' || previousOptionClass != currentOptionClass){        	    	   
    	   if ($(this).is(":checked")) {           	   
           optionsCheckboxCount = optionsCheckboxCount + 1;         
           previousOptionClass = $(this).attr('title');           
           }  
           }    	  
           }); 
           
           if(optionsCheckboxCount == classNumItems){
       	   $('#attribute-values').hide();
		   $('#bulk-images-price').show();          
           $('#btn_configurable_product_back').removeAttr('disabled');
           $('#bulk-images-price-status').addClass('active');  
           $('#attribute-options-error').hide(); 

           
           // To empty attribute values list
           $('#bulk-images-list').empty();
           // To submit select attribute form
           $('#configurable_options_form').submit(); 
                    	                
     
       }else{
       $('#attribute-options-error').show();          
       } 
           
           }
           if($('#select-attribute').is(":visible")){
               var checkboxFlag = 0;        
        	   $(".attribute-checkbox").each(function(){
        	   if ($(this).is(":checked")) { 
            	   if(checkboxFlag == 0){            	   
        		   $('#select-attribute').hide();  
                   $('#attribute-values').show();            
                   $('#btn_configurable_product_back').removeAttr('disabled');
                   $('#attribute-values-status').addClass('active');  
                   $('#select-attributes-error').hide();   
                   checkboxFlag = 1; 
            	 }  
               }
               });  
           if(checkboxFlag == 0){          	                
           $('#select-attributes-error').show();
           }else{
               // To empty attribute values list
               $('#attribute-values-list').empty();
               // To submit select attribute form
               $('#configurable_attribute_form').submit();       
           } 
           }                    	   
   	       });

    	   $('#btn_configurable_product_back').on('click', function(e) {

    	   $('#btn_configurable_product_next').show();
    	   $('#btn_configurable_product_generate').hide();	   
        	   
    	   if($('#attribute-values').is(":visible")){
    	   $('#attribute-values-status').removeClass('active');
           $('#attribute-values').hide();  
    	   $('#select-attribute').show();
    	   $('#btn_configurable_product_back').attr('disabled','disabled');
    	   $('#attribute-options-error').hide();           
    	   }    	
    	   if($('#bulk-images-price').is(":visible")){
    	   $('#bulk-images-price-status').removeClass('active');
       	   $('#bulk-images-price').hide();  
       	   $('#attribute-values').show();       
           }
    	   if($('#summary').is(":visible")){
    	   $('#summary-status').removeClass('active');
           $('#summary').hide();  
           $('#bulk-images-price').show(); 
           $('#next_span_menu').html($('#next_span_menu_label').val());  
           }              	     
           });          
    	     
           
            // Toggle effect create configurable product              
    	    $('#btn_configurable_product').on('click', function(e) {        
    	    if($('#form_product_validate').valid() == false){ 
    	    return false;              
            }               	        
    	    $('.configurable-product-form').toggle("slide", {
    	    direction: "right"
    	    }, 1000);    	    
    	    });
    	    
    	    $('#btn_configurable_product_cancel').on('click', function(e) {
    	        $('.configurable-product-form').toggle("slide", {
    	             direction: "right"
    	         }, 1000);
    	    $('#btn_configurable_product_back').attr('disabled','disabled');   
    	    $('#select-attribute').show(); 
        	$('#attribute-values').hide(); 
        	$('#bulk-images-price').hide();
        	$('#summary').hide();

        	$('#attribute-values-status').removeClass('active');
        	$('#bulk-images-price-status').removeClass('active');
        	$('#summary-status').removeClass('active'); 
    	    });

    	    // Update configurable attributes
    	    $( document ).ready(function() {
    	    var productType = $('#product_type').val();
    	    var isConfigurableProduct = $('#is_configurable_product').val();    	    
    	    
            if(productType == 'configurable' || isConfigurableProduct == 1){
            	$('#qty').attr('disabled','disabled');   
            	$('#qty').hide();    
                $('#special_price_section').hide();                      
    	    var attributeSetId = $('#default_attribute_set_id').val();
    	    var currentProductId = $('#current_product_id').val();   	   
    	    $('#configurable-product-loader').show();  
     	        $.ajax({
       	         type: "POST",
       	         url: $('#configurable_attributes_ajax_url').val(),
       	         data: {attribute_set_id: attributeSetId,current_product_id: currentProductId},
       	         success: function(transport){                                        
       	         $('#select-attributes-list').html(transport); 
       	         $('#configurable-product-loader').hide(); 
       	         }
       	         }); 
            }
    	    });
    	
    	    $('#attribute_set').on('change', function(e) {    	    	
        	var productType = $('#product_type').val();
        	if(productType == 'configurable'){  	         	  		
    		var attributeSetId = $('#default_attribute_set_id').val(); 
    		if(attributeSetId){
    		attributeSetId = $('#default_attribute_set_id').val();	
        	}  
    		var currentProductId = $('#current_product_id').val();    		
    		 $('#configurable-product-loader').show();   		    		
    	     $.ajax({
    	         type: "POST",
    	         url: $('#configurable_attributes_ajax_url').val(),
     	         data: {attribute_set_id: attributeSetId,current_product_id: currentProductId},
    	         success: function(transport){                                        
    	         $('#select-attributes-list').html(transport); 
    	         $('#configurable-product-loader').hide(); 
    	         }
    	         }); 
        	} 
    	    });  

    	    $('#product_type').on('change', function(e) {    	    	
            	var productType = $('#product_type').val();
            	if(productType == 'configurable'){ 
                    $('#qty').attr('disabled','disabled');  
                    $('#qty').hide(); 
                    $('#special_price_section').hide();        
                                
                $('#marketplace-configurble-product-content').show();  		
        		var attributeSetId = $('#default_attribute_set_id').val(); 
        		if(attributeSetId){
        		attributeSetId = $('#default_attribute_set_id').val();	
            	}   	
        		var currentProductId = $('#current_product_id').val();  
        		 $('#configurable-product-loader').show(); 	    		
        	     $.ajax({
        	         type: "POST",
        	         url: $('#configurable_attributes_ajax_url').val(),
         	         data: {attribute_set_id: attributeSetId,current_product_id: currentProductId},
        	         success: function(transport){                                        
        	         $('#select-attributes-list').html(transport); 
        	         $('#configurable-product-loader').hide(); 
        	         }
        	         }); 
            	}else{
            	$('#qty').removeAttr('disabled','disabled');
            	$('#qty').show();
                $('#special_price_section').show();                 
                $('#marketplace-configurble-product-content').hide(); 
                } 
        	    });

    	      // Ajax for get configurable attributes value
    	       $("#configurable_attribute_form").on('submit',(function(e){
    	           e.preventDefault();          
    	               $('#configurable-product-loader').show();
    	               $.ajax({
    	                   url: $('#configurable_options_ajax_url').val(), 
    	                   type: 'POST',     
    	                   success: function (transport) {               
    	                   $('#attribute-values-list').html(transport);
    	                   $('#configurable-product-loader').hide();     
    	              
    	                   },
    	                   data: new FormData(this),
    	                   cache: false,
    	                   contentType: false,
    	                   processData: false
    	               });
    	     
    	           }));

    	       // Ajax Configurable attibutes option values for bulk images & price 
    	       $("#configurable_options_form").on('submit',(function(e){
    	           e.preventDefault();          
    	               $('#configurable-product-loader').show();
    	               $.ajax({
    	                   url: $('#configurable_bulk_ajax_url').val(), 
    	                   type: 'POST',     
    	                   success: function (transport) {               
    	                   $('#bulk-images-list').html(transport);
    	                   $('#configurable-product-loader').hide();      	              
    	                   },
    	                   data: new FormData(this),
    	                   cache: false,
    	                   contentType: false,
    	                   processData: false
    	               });
    	     
    	           }));    	       	       	    
            });

 
       
       
  </script>
<?php } ?>

<input type="hidden"
	value="<?php echo $block->getConfigurableAttributesUrl(); ?>"
	name="configurable_attributes_ajax_url"
	id="configurable_attributes_ajax_url" />

<input type="hidden"
	value="<?php echo $block->getConfigurableOptionsUrl(); ?>"
	name="configurable_options_ajax_url" id="configurable_options_ajax_url" />

<input type="hidden"
	value="<?php echo $block->getConfigurableBulkUrl(); ?>"
	name="configurable_bulk_ajax_url" id="configurable_bulk_ajax_url" />

<input type="hidden" value="<?php echo $block->getAttributeSetId(); ?>"
	name="default_attribute_set_id" id="default_attribute_set_id" />
