<?php use Magento\Framework\App\Action\Action; ?>
<?php if (($_products = $this->getProductCollection()) && $_products->getSize()): ?>

	<div class="cwsFeatured">
		<?php //if($this->getShowHeading()): ?>
			<!--<div class="title"><h3><?php //echo "Featured Products";//echo __($this->getHeading()) ;?></h3></div> -->

		<?php //endif; ?>

		<div class="title1"><h1></h1><?php echo "Featured Products"; ?></h1></div>

		<?php
			$_products = $this->getProductCollection();
			$limit=$this->getNoOfProduct();
			if($limit==0){
				$limit=10;
			}
			$_helper = $this->helper('Magento\Catalog\Helper\Output');
   
			$viewMode = 'grid';
			$image = 'category_page_grid';
			$showDescription = false;
			$templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
			
			/*** Position for actions regarding image size changing in vde if needed */
			$pos = $block->getPositioned();
			$position = '';
			if ($pos != null) {
				$position = ' style="left:'.$block->getVar("{$image}:width").'px;'.'top:'.$block->getVar("{$image}:height").'px;"';
			}
		?>
		<?php if($this->getShowSlider()) { ?>
			<div id="cwsFpSlider" class="products wrapper <?php echo $viewMode; ?> products-<?php echo $viewMode; ?>">
		<?php } else { ?>
			<div class="products wrapper <?php echo $viewMode; ?> products-<?php echo $viewMode; ?> grid<?php echo $this->getProductsPerRow(); ?>">
		<?php } ?>
			<ul class="products list items product-items">
				<?php
					$iterator = 1;
					$count=0;
					$i=0;
					foreach ($_products as $_product):
						if($limit>$count){
						$count++;
				?>
				<?php  echo($iterator++ == 1) ? '<li class="item product product-item">' : '</li><li class="item product product-item">' ?>
					<div class="product-item-info" data-container="product-grid">
						<?php $productImage = $block->getImage($_product, $image);?>
						<a href="<?php echo $_product->getProductUrl() ?>" class="product photo product-item-photo" tabindex="-1"><?php echo $productImage->toHtml(); ?></a>
						<div class="product details product-item-details">
							<?php $_productNameStripped = $block->stripTags($_product->getName(), null, true); ?>
							<strong class="product name product-item-name"><a class="product-item-link" href="<?php echo $_product->getProductUrl() ?>"><?php echo $_helper->productAttribute($_product, $_product->getName(), 'name'); ?></a></strong>
							<?php if($this->getProductsPrice()): ?>
								<?php echo $block->getProductPrice($_product) ?>
							<?php endif; ?>
							<div class="product-item-inner">
								<div class="product actions product-item-actions"<?php echo strpos($pos, $viewMode . '-actions') ? $position : ''; ?>>
									<?php if($this->getAddToCart()): ?>
										<div class="actions-primary"<?php echo strpos($pos, $viewMode . '-primary') ? $position : ''; ?>>
									<?php endif; ?>
										<?php if ($_product->isSaleable()): ?>
											<?php $postParams = $block->getAddToCartPostParams($_product); ?>
											<form data-role="tocart-form" action="<?php echo $postParams['action']; ?>" method="post" data-mage-init='{"validation":{}}'>
												<input type="hidden" name="product" value="<?php echo $postParams['data']['product']; ?>">
												<input type="hidden" name="<?php echo Action::PARAM_NAME_URL_ENCODED; ?>" value="<?php echo        $postParams['data'][Action::PARAM_NAME_URL_ENCODED]; ?>">
												 <?php echo $block->getBlockHtml('formkey')?>
												<?php if (($_product->isSaleable())&&($this->getAddToCart())) { ?>
													<button type="submit" title="<?php echo $block->escapeHtml(__('Add to Cart')); ?>" class="action tocart primary"> <span><?php echo __('Add to Cart') ?></span> </button>
												<?php } ?>
											</form>
										<?php else: ?>
											<?php if ($_product->getIsSalable()): ?>
												<div class="stock available"><span><?php echo __('In stock') ?></span></div>
											<?php else: ?>
												<div class="stock unavailable"><span><?php echo __('Out of stock') ?></span></div>
											<?php endif; ?>
										<?php endif; ?>
										<?php if($this->getAddToCart()): ?>
											</div>
										<?php endif; ?>
										<?php if($this->getAddToWishlist() || $this->getAddToCompare()): ?>
											<div data-role="add-to-links" class="actions-secondary"<?php echo strpos($pos, $viewMode . '-secondary') ? $position : ''; ?>>
												<?php if($this->getAddToWishlist()): ?>
													<?php if ($this->helper('Magento\Wishlist\Helper\Data')->isAllow()): ?>
														<a href="#" class="action towishlist" title="<?php echo $block->escapeHtml(__('Add to Wishlist')); ?>" aria-label="<?php echo $block->escapeHtml(__('Add to Wishlist')); ?>" data-post='<?php echo $block->getAddToWishlistParams($_product); ?>' data-action="add-to-wishlist" role="button"><span><?php echo __('Add to Wishlist') ?></span></a>
													<?php endif; ?>
												<?php endif; ?>
												<?php if($this->getAddToCompare()): ?>
													<?php $compareHelper = $this->helper('Magento\Catalog\Helper\Product\Compare'); ?>
													<a href="#" class="action tocompare" title="<?php echo $block->escapeHtml(__('Add to Compare')); ?>" aria-label="<?php echo $block->escapeHtml(__('Add to Compare')); ?>" data-post='<?php echo $compareHelper->getPostDataParams($_product); ?>' role="button"><span><?php echo __('Add to Compare') ?></span></a>
												<?php endif; ?>
											</div>
										<?php endif; ?>
									</div>
									<?php if(!$this->getShowSlider()) { ?>
										<?php if ($this->getDescription()):?>
											<div class="product description product-item-description">
												<?php echo $_helper->productAttribute($_product, $_product->getShortDescription(), 'short_description') ?>
												<a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $_productNameStripped ?>" class="action more"><?php echo __('Learn More') ?></a>
											</div>
										<?php endif; ?>
									<?php } ?>
								</div>
							</div>
						</div>
					<?php echo($iterator == count($_products)+1) ? '</li>' : '' ?>
				<?php } endforeach; ?>
			</ul>





		</div>

<?php echo $block->getToolbarHtml() ?>
		
	<?php if($this->getShowSlider()): ?>
		<?php if($this->getNavarrow()): ?>
			<a href="#" class="cwsFp-prev"></a> <a href="#" class="cwsFp-next"></a>
		<?php endif ?>
		<?php if($this->getPagination()): ?>
			<div class="cwsFp-pagination"></div>
		<?php endif ?>
		<?php if ($block->getPagerHtml()): ?>
			<div class="toolbar bottom"><?php echo $block->getPagerHtml(); ?></div>
		<?php endif ?>

		<script type="text/javascript">
			requirejs(['jquery','domReady!','cwsjcarousel'], function($){			
					
						var jcarousel = $('#cwsFpSlider');
						jcarousel.on('jcarousel:reload jcarousel:create', function () {
							var carousel = $(this),
								cntWidth = $('#maincontent .columns').width()-60;
								if($( window ).width() < 767){
									carousel.css('width', cntWidth + 'px');
								} else {
									carousel.css('width', 'auto');
								}
								
								width = carousel.innerWidth();
								//alert(cntWidth);	
							
							if (width >= 840) { width = width / 4-17; }
							else if (width >= 650) { width = width / 3-16; }
							else if (width >= 340) { width = width / 2-13; }
							else if (width >= 200) { width = width / 1; }
			
							carousel.jcarousel('items').css('width', Math.ceil(width) + 'px');
							
						}).jcarousel({ wrap: 'circular' });
							
						$('.cwsFeatured').jcarouselAutoscroll({ autostart:'<?php if($this->getAutoscroll()){echo true;} else{echo false;}?>'});
						$('.cwsFp-prev').jcarouselControl({ target: '-=1' });
						$('.cwsFp-next').jcarouselControl({ target: '+=1' });
			
						$('.cwsFp-pagination').on('jcarouselpagination:active', 'a', function() {
							$(this).addClass('active');
						}).on('jcarouselpagination:inactive', 'a', function() {
							$(this).removeClass('active');
						}).on('click', function(e) {
							e.preventDefault();
						}).jcarouselPagination({
							perPage: 1,
							item: function(page) { return '<a href="#' + page + '">' + page + '</a>'; }
						});
			});	
		</script>
	<?php endif ?>
</div>
		</div>




	



 <?php if (!$block->isRedirectToCartEnabled()) : ?>
       <script type="text/x-magento-init">
        {
            "[data-role=tocart-form], .form.map.checkout": {
                "catalogAddToCart": {}
            }
        }
        </script>
    <?php endif; ?>
<?php endif; ?>






