

<?php /**
 *   Wordpress post collection for magento homepage
 */

    $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
    $postInstance = $objectManager->get('FishPig\WordPress\Model\Post');
    $posts = $postInstance->getCollection()
            ->addFieldToFilter('post_status','publish')  //only published posts
            ->addFieldToFilter('id',array('nin'=>2))  //for ignoring sample post
            ->setPageSize(7);
            /*->setCurPage(1);*/
?>

<?php //var_dump($posts->getData()); ?>  


<div class="column main">
  <div class="latest-post">
      <h1><?php echo __('Latest From Our Blog')?></h1>
      <span class="blog-title"><?php //echo __('Latest From Our Blog')?></span>
      <!-- =============================== code for collage ============================================== -->

      <div class="mosaicflow">
        <?php



        foreach($posts as $i=>$po):?>
            <div class="mosaicflow__item">
             <a href="<?php echo $po->getUrl()?>">
              <?php if ($image = $po->getImage()) {
                  $postImage = $image->getFullSizeImage();
                }else{
                  $postImage = '';
                }
               ?>
                <div class="post-image1"><img src="<?php echo $postImage;?>"/></div>
               <div class="post-detail-group1">
                  <span class="article-signq"><?php //echo __('Special Introductory Price');?></span>
                  <span class="post-title-listq">
                      <?php echo $po->getPostTitle();?></span><br>
                   <?php echo $po->getData('post_content');?></span>
                   <br>
                </div>
            </div>
        <?php
        endforeach;
        ?>

      </div>

      <!-- ===============================    end code      ============================================== -->
      <div class="customNavigation">
        <a class="btn previous-recipes"><i class="fa fa-chevron-left" aria-hidden="true"></i></a>
        <a class="btn next-recipes"><i class="fa fa-chevron-right" aria-hidden="true"></i></a>
      </div>
  </div>
</div>
<style type="text/css">
    /*.previous-recipes , .next-recipes {
        cursor: pointer;
    }
    .owl-item .item {
        width : 100%;
    }*/
</style>
<script type="text/javascript">
    require(['jquery','mosaicflow'],function($){
      $('.mosaicflow').mosaicflow({

      });
    });
</script>
