<?php
// @codingStandardsIgnoreFile
?>
<div class="item link compare" data-bind="scope: 'compareProducts'" data-role="compare-products-link">
    <a class="action compare no-display" title="<?php /* @escapeNotVerified */ echo __('Compare Products') ?>"
       data-bind="attr: {'href': compareProducts().listUrl}, css: {'no-display': !compareProducts().count}"
    >
        <?php /* @escapeNotVerified */ echo __('Compare Products') ?>
        <span class="counter qty" data-bind="text: compareProducts().countCaption"></span>
    </a>
</div>
<script type="text/x-magento-init">
{"[data-role=compare-products-link]": {"Magento_Ui/js/core/app": <?php /* @escapeNotVerified */ echo $block->getJsLayout();?>}}
</script>


<div class="uper-link">

   <?php  $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
    $storeManager = $objectManager->get('\Magento\Store\Model\StoreManagerInterface');
    $baseurllink = $storeManager->getStore()->getBaseUrl();
    //echo $baseurllink;


   ?>

    <!--<?php //echo $baseurllink; ?>customer/account/login/ -->
    <span><a href="<?php echo $baseurllink; ?>customer/account/"><?php echo "Account"; ?></a></span>
    <span><a href="<?php echo $baseurllink; ?>wishlist/"><?php echo "Wishlist"; ?></a></span>
    <span><a href="<?php echo $baseurllink; ?>customer/account/login/"><?php echo "Log In"; ?></a></span>
    <span><a href="<?php echo $baseurllink; ?>customer/account/create/"><?php echo "Sign Up"; ?></a></span>
    <span><?php //echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('block_header_top_left')->toHtml();?></span>
    <span class="ic ic-lg ic-phone"></span>Call +001 555 801 
</div>








