<?php
/**
 * Apptha
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://www.apptha.com/LICENSE.txt
 *
 * ==============================================================
 *                 MAGENTO EDITION USAGE NOTICE
 * ==============================================================
 * This package designed for Magento COMMUNITY edition
 * Apptha does not guarantee correct work of this extension
 * on any other Magento edition except Magento COMMUNITY edition.
 * Apptha does not provide extension support in case of
 * incorrect edition usage.
 * ==============================================================
 *
 * @category    Apptha
 * @package     Apptha_Marketplace
 * @version     1.1
 * @author      Apptha Team <developers@contus.in>
 * @copyright   Copyright (c) 2016 Apptha. (http://www.apptha.com)
 * @license     http://www.apptha.com/LICENSE.txt
 *
 */
?>
<?php /** @var $block \Magento\Customer\Block\Account\Navigation */ ?>
<?php
$sellerGroupId=$customerId=$customerGroupId=$status='';
$urlInterface = \Magento\Framework\App\ObjectManager::getInstance ()->get ( 'Magento\Framework\UrlInterface' );
$currentUrl = $urlInterface->getCurrentUrl ();
$objectGroupManager = \Magento\Framework\App\ObjectManager::getInstance ();
$customerSession = $objectGroupManager->get ( 'Magento\Customer\Model\Session' );
$customerDatas = $customerSession->getCustomer ();
if ($customerSession->isLoggedIn ()) {
    $customerId = $customerSession->getId ();
    $customerGroupId = $customerDatas->getGroupId ();
    $customerGroupSession = $objectGroupManager->get ( 'Magento\Customer\Model\Group' );
    $customerGroupData = $customerGroupSession->load ( $customerGroupId );
    $sellerGroupCode = $customerGroupData->getCode ();
    $sellerGroupData = $customerGroupSession->load ( 'Marketplace Seller', 'customer_group_code' );
    $sellerGroupId = $sellerGroupData->getId ();
    $customerGroupSession = $objectGroupManager->get ( 'Apptha\Marketplace\Model\Seller' );
    $status = $customerGroupSession->load ( $customerId, 'customer_id' )->getStatus ();
}

$reviewSellerId = $this->getRequest ()->getParam ( 'seller_id' );
?>
 <?php 
        $helper = $objectGroupManager->get ( 'Apptha\Marketplace\Helper\System' );
        $domain=$helper->checkMarketplaceKey();
        if($domain!=1){
            echo  $keyerror =  $helper->getLicensekeyMessage();
        }
       if($domain==1){ 
?>
<div class="block block-collapsible-nav"
	<?php if(!empty($reviewSellerId)){ echo 'style="display:none;"'; } ?>>
	<div class="title block-collapsible-nav-title">
		<strong><?php echo __('MARKETPLACE'); ?></strong>
	</div>
	<div class="content block-collapsible-nav-content"
		id="block-collapsible-navigation">
		<ul class="nav items">
			<li class="nav item "><strong><?php echo __('MARKETPLACE'); ?></strong></li>
        <?php
        $objectModelManager = \Magento\Framework\App\ObjectManager::getInstance ();
        $seller = $objectModelManager->get ( 'Apptha\Marketplace\Helper\Data' );
        $assignProduct = $seller->getAssignProduct ();
        $isSellerReviewEnabled = $seller->isSellerReviewEnabled ();
       if ($customerGroupId != $sellerGroupId || $status == 0) {
            ?>
        <li
				class="nav item <?php if($currentUrl==$block->getUrl('marketplace/general/changebuyer')){?>current<?php }?>"><a
				href="<?php echo $block->getUrl('marketplace/general/changebuyer') ?>"><?php echo __('Become a Seller'); ?></a></li><?php }?>
        <?php if($customerGroupId==$sellerGroupId && $status==1){ ?>
        <li
				class="nav item <?php if($currentUrl==$block->getUrl('marketplace/seller/dashboard')){?>current<?php }?>"><a
				href="<?php echo $block->getUrl('marketplace/seller/dashboard') ?>"><?php echo __('Seller Dashboard'); ?></a></li>
			<li
				class="nav item <?php if($currentUrl==$block->getUrl('marketplace/product/manage')|| $currentUrl==$block->getUrl('marketplace/product/add')){?>current<?php }?>"><a
				href="<?php echo $block->getUrl('marketplace/product/manage') ?>"><?php echo __('Manage Products'); ?></a></li>
        <?php if($assignProduct){?>
        <li
				class="nav item <?php if($currentUrl==$block->getUrl('marketplace/assignproduct/manage')|| $currentUrl==$block->getUrl('marketplace/assignproduct/search')){?>current<?php }?>"><a
				href="<?php echo $block->getUrl('marketplace/assignproduct/manage') ?>"><?php echo __('Assign Product'); ?></a></li>
        <?php }?>
        <li
				class="nav item <?php if($currentUrl==$block->getUrl('marketplace/seller/profile')){?>current<?php }?>"><a
				href="<?php echo $block->getUrl('marketplace/seller/profile') ?>"><?php echo __('My Store'); ?></a></li>
			<li
				class="nav item <?php if($currentUrl==$block->getUrl('marketplace/order/manage')){?>current<?php }?>"><a
				href="<?php echo $block->getUrl('marketplace/order/manage') ?>"><?php echo __('Order Management'); ?></a></li>
			<li
				class="nav item <?php
            $objectManager = \Magento\Framework\App\ObjectManager::getInstance ();
            $requestInterface = $objectManager->get ( 'Magento\Framework\App\RequestInterface' );
            $routeName = $requestInterface->getRouteName ();
            $controllerName = $requestInterface->getControllerName ();
            $actionName = $requestInterface->getActionName ();
            if ($currentUrl == $block->getUrl ( 'marketplace/seller/transactions' ) || $routeName == 'marketplace' && $controllerName == 'seller' && $actionName == 'transactions') {
                ?>current<?php }?>"><a
				href="<?php echo $block->getUrl('marketplace/seller/transactions') ?>"><?php echo __('Transactions'); ?></a></li>
        <?php if($isSellerReviewEnabled == 1){ ?> 
        <li
				class="nav item <?php if($currentUrl==$block->getUrl('marketplace/seller/review')){?>current<?php }?>"><a
				href="<?php echo $block->getUrl('marketplace/seller/review') ?>"><?php echo __('Reviews'); ?></a></li>
        <?php } ?>
       <?php
            $adminApproval = $seller->getContactAdmin ();
            if ($adminApproval) {
                ?>
        <li
				class="nav item <?php if($currentUrl==$block->getUrl('marketplace/contact/form')){?>current<?php }?>"><a
				href="<?php echo $block->getUrl('marketplace/contact/form') ?>"><?php echo __('Contact Admin'); ?></a></li>
       <?php }?>
       <?php
            $isSellerSubscriptionEnabled = $seller->isSellerSubscriptionEnabled ();
            if ($isSellerSubscriptionEnabled) {
                ?>
       <li
				class="nav item <?php if($currentUrl==$block->getUrl('marketplace/seller/subscriptionplans')){?>current<?php }?>"><a
				href="<?php echo $block->getUrl('marketplace/seller/subscriptionplans') ?>"><?php echo __('Subscription Plans'); ?></a></li>
       <?php
            }
            ?>      
       <?php }?>       
        </ul>
	</div>
</div>
<?php }?>
